### ISSUE TITLE
Advisory: Sample advisory submission

### ISSUE THREAD

**Issue by ken-duck** [OSSIndex/vulns#1]
URL: https://github.com/jquery/jquery/issues/3133
  format: npm
  namespace:
  name: jquery
  versions: >=2.1.0 < 2.2.4

**Comment by OrangeDog** [comment]
You should set up proper issue templates with labels. That would be a lot easier (and impossible to overlook).

**Comment by ken-duck** [comment]
@OrangeDog You are quite correct. It has been mentioned a couple of times before and I have been putting it off due to a number of other issues I have been dealing with. You are right, though, that it would make things much easier so I will endeavour to finally make those changes (tonight if possible).

**Comment by Rmumford52** [comment]
Mr. James,
It means that your one good man who has the knowledge and your very
smart.....and that's why everyone depends upon you.  Also, everyone trusts
you only.....

**Comment by ken-duck** [comment]
We *finally* have templates (about time!).
