### ISSUE TITLE
unicode

### ISSUE THREAD

**Issue by kellyselden** [OSSIndex/vulns#101]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/vuln/59249e8d-13f1-43ca-9898-5f71f16a57f1
```

**Description**
It is missing a version range (0.0.0,).
NPM says "Update to version 9.0.0 or later"

**Comment by ken-duck** [comment]
Thanks for the heads up. This has been resolved and should be visible sometime tomorrow.

**Comment by ken-duck** [comment]
Verified as fixed: https://ossindex.sonatype.org/vuln/59249e8d-13f1-43ca-9898-5f71f16a57f1
