### ISSUE TITLE
http-proxy

### ISSUE THREAD

**Issue by kellyselden** [OSSIndex/vulns#102]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/vuln/1f994e13-0084-4c73-a171-2e929bababbd
```

**Description**
It should be "Upgrade to version 1.18.1 or later" https://www.npmjs.com/advisories/1486
but is `(0.0.0,)`

**Comment by ken-duck** [comment]
Thanks for the heads up. This has been resolved and should be visible sometime tomorrow.

**Comment by mum-viadee** [comment]
Hi @ken-duck, you commented this issue 7 days ago, but the mentioned fix still isn't visible.

**Comment by ken-duck** [comment]
Bugger. I will check this out and shepherd it though.

**Comment by mum-viadee** [comment]
> Bugger. I will check this out and shepherd it though.

Thanks. The fix is now visible.  @kellyselden, the bug can be closed.

**Comment by ken-duck** [comment]
Splendid. Thanks for the help!
