### ISSUE TITLE
Incorrect vulnerability details - Hangfire XSS has been fixed in 1.6.26

### ISSUE THREAD

**Issue by andyrooger** [OSSIndex/vulns#104]
**Vulnerability URL**

```
https://ossindex.sonatype.org/vuln/e539f733-0e76-4118-b5e9-8f3b59d48cec
```

**Description**

The affected version range is flagging all 1.6.x versions as vulnerable. As per the [github issue link](https://github.com/HangfireIO/Hangfire/issues/1441#issuecomment-495243197), the problem has been fixed in both latest 1.6.x and 1.7+.

**Comment by ken-duck** [comment]
I am cleaning up some old issues. This was resolved some time ago, but I neglected to update the issue. https://ossindex.sonatype.org/vuln/e539f733-0e76-4118-b5e9-8f3b59d48cec
