### ISSUE TITLE
lodash Npmjs advisory #1523

### ISSUE THREAD

**Issue by GoldFlsh** [OSSIndex/vulns#105]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://www.npmjs.com/advisories/1523
  format: npmjs
  namespace: public
  name: lodash
  versions: 0.1.0 - 4.17.15
```

**More information**
Overview
All versions of lodash are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.

This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

Remediation
No fix is currently available. Consider using an alternative package until a fix is made available.

https://hackerone.com/reports/712065
https://github.com/lodash/lodash/issues/4744

**Comment by GoldFlsh** [comment]
I assume this is related to this issue - 
https://github.com/OSSIndex/vulns/issues/92

**Comment by ken-duck** [comment]
It is. We are still working on a full fix (things are rather hectic; we have some big new code that will fix a lot of these going forward, but there is a lot that needs to be in place to fix it). Meanwhile I think this new one should show up in the next day or so.

Sorry for the delay.

**Comment by ken-duck** [comment]
Closing old issues. Validation that this data is available in the public DB: https://ossindex.sonatype.org/vuln/eeedfb1c-6a5e-428c-bb17-c64b66f9eced?component-type=npm&component-name=lodash
