### ISSUE TITLE
Incorrect vulnerability details

### ISSUE THREAD

**Issue by jabscuan** [OSSIndex/vulns#114]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/b7740d41-fc85-4d22-8af5-5a3159e114ea
https://ossindex.sonatype.org/vuln/7ccaaed0-205b-4382-a963-8a30a0b151b1

**Description**
OSSIndex marks yargs-parser@5.0.0-security  with a vulnerability while the npm advisory it links to says 5.0.0 is fine.
https://ossindex.sonatype.org/component/pkg:npm/yargs-parser@5.0.0-security.0
https://www.npmjs.com/advisories/1500

**Comment by ken-duck** [comment]
Ah, I see. It appears that 5.0.0 is vulnerable, but 5.0.0.security.0 is not. I will resolve the issue. It should show up in the public feed by sometime tomorrow.

**Comment by ken-duck** [comment]
Clearing some older issues. This appears to have been resolved.
