### ISSUE TITLE
Missing Handlebars Prototype Pollution SNYK-JS-HANDLEBARS-173692

### ISSUE THREAD

**Issue by greggawatt** [OSSIndex/vulns#116]
**Advisory details**
```
  URL: https://www.npmjs.com/advisories/755, https://snyk.io/vuln/SNYK-JS-HANDLEBARS-173692
  format: NPM
  namespace: NPM scope
  name: Handlebars
  versions: <4.0.14 || >=4.1.0 <4.1.2
```

**More information**
None

**Comment by ken-duck** [comment]
Just cleaning up old tickets. This has been resolved for some time. https://ossindex.sonatype.org/vuln/0832a560-9148-44e9-9008-9b4897d1c80c?component-type=npm&component-name=handlebars
