### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/7ea56ad4-8a8b-4e51-8ed9-5aad83d8efb1?component-type=maven&component-name=junit.junit

### ISSUE THREAD

**Issue by marcphilipp** [OSSIndex/vulns#127]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/7ea56ad4-8a8b-4e51-8ed9-5aad83d8efb1?component-type=maven&component-name=junit.junit

**Description**
The vulnerability was fixed in 4.13.1 but shows 4.13.1 as being affected.

**Source**
https://github.com/advisories/GHSA-269g-pwp5-87pp

**Comment by ken-duck** [comment]
Sorry for the delay. This appears to be a case where the CVE was changed but OSS Index did not notice the range change. Thanks for bringing it to our attention, this should be fixed in the public repo by tomorrow.

**Comment by marcphilipp** [comment]
Thanks, it's gone now. 👍

**Comment by ken-duck** [comment]
Outstanding. Thanks for the update (and the initial report!)
