### ISSUE TITLE
Vulnerabilities for the package pkg:npm/collection-visit disappeared

### ISSUE THREAD

**Issue by missingdays** [OSSIndex/vulns#13]
Our system recored that previously Sonatype returned
```
CVE: CWE-400
CVSS Score: 7.5
Reference: https://ossindex.sonatype.org/vuln/a917ab55-851f-4c8b-ac82-6f988881c329
Description: The software does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended.
```
But now there are no vulnerabilities reported by the sonatype: https://ossindex.sonatype.org/component/pkg:npm/collection-visit
Was the old data incorrect? Or is it bug?

**Comment by ken-duck** [comment]
I have been doing some looking around the database and am having troubles finding indications that we had that vulnerability assigned to that package (or history tables do not show that it was there). Perhaps there is a bug in one of our client tools. Were you using one of the OSS Index integrations, or was this through a custom integration?

**Comment by missingdays** [comment]
@ken-duck we are using REST API

**Comment by ken-duck** [comment]
I have looked around some more in our history data and cannot find indication that this vulnerability was reported against the collection-visit package. If you see it show up again please let me know and I might be able to trace the cause.

Sorry I could not be more helpful in this case.
