### ISSUE TITLE
Bug: Wrong component assigned to many vulnerabilities

### ISSUE THREAD

**Issue by bykes** [OSSIndex/vulns#134]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/vuln/1205a1ec-0837-406f-b081-623b9fb02992
https://ossindex.sonatype.org/vuln/b85a00e3-7d9b-49cf-9b19-b73f8ee60275
https://ossindex.sonatype.org/vuln/3f596fc0-9615-4b93-b30a-d4e0532e667f
https://ossindex.sonatype.org/vuln/292c11e9-cf66-4d76-aaf7-b63a091f8891
https://ossindex.sonatype.org/vuln/af22d349-929c-41ae-ba6c-2f7b507026f0
https://ossindex.sonatype.org/vuln/ab9013f0-09a2-4f01-bce5-751dc7437494
https://ossindex.sonatype.org/vuln/4f7e98ad-2212-45d3-ac21-089b3b082e6c
https://ossindex.sonatype.org/vuln/fc1e8802-77e5-458f-b987-eb778c6ac2fc
https://ossindex.sonatype.org/vuln/5113110f-3321-491d-9506-447a3361f9cd
https://ossindex.sonatype.org/vuln/3242fdc1-bfe9-46a6-af0c-0b8f57f56eb7
https://ossindex.sonatype.org/vuln/6ce886d0-2dfd-4cef-b9a4-2fb400baf5ef
https://ossindex.sonatype.org/vuln/008dd13c-dede-46f4-b103-f72bdbae725e
https://ossindex.sonatype.org/vuln/ed6fd4f6-b25f-494e-b4e3-ef10deff7d39
```

**Description**
All above vulnerabilities are valid for: 
com.fasterxml.jackson.core.jackson-core
com.fasterxml.jackson.core.jackson-databind
but are not valid for 
org.codehaus.jackson.jackson-mapper-asl

org.codehaus.jackson.jackson-mapper-asl is completly different library with completly differen verision numbers.
In OSS db fasterxml version numbers are applied to codehaus library.

Please remove org.codehaus.jackson.jackson-mapper-asl from the list of affected libraries for all above vulnerabilities.

**Comment by msymons** [comment]
> org.codehaus.jackson.jackson-mapper-asl is completly different library with completly differen verision numbers.

This is incorrect.  The newer is derived from the older  (ie, project migrated away from codehaus).

Jackson 1.x called the databinding part "mapper" (there's both mapper-asl and mapper-lgpl, the only diff being which LICENSE file/declaration was included).

Polymorphic deserialization was added in 1.5 and thus any deserialization threat that affects "jackson-databind before 2.x" also affects jackson-mapper-asl 1.5 onwards.

**Comment by bykes** [comment]
thanks for clarification
closing in that case
