### ISSUE TITLE
Incorrect vulnerability details OSSINDEX-947a-6189-d205

### ISSUE THREAD

**Issue by NioXen** [OSSIndex/vulns#136]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vuln/028f6056-4710-427e-bcf8-947a6189d205?component-type=npm&component-name=object-path
```

**Description**
The NPM advisory which is linked from the vulnerability states that upgrading to version 0.11.5 will address the vulnerability (https://www.npmjs.com/advisories/1573) however, the entry on ossindex implies that 0.11.5 is still vulnerable.
It looks as though 0.11.5 was specifically released to address this vulnerability (I could be wrong here)

Thank you

**Comment by ken-duck** [comment]
Sorry for the delay. We have fixed the issue and it should show up sometime tomorrow. Thanks for the heads up!

**Comment by ken-duck** [comment]
Visual confirmation indicates that 0.11.5 is no longer considered vulnerable: https://ossindex.sonatype.org/component/pkg:npm/object-path@0.11.5
