### ISSUE TITLE
DCB_ASSOCIATION:Y3890K40FJF4UG3QP8AOBT4LG3SRNCIOP

### ISSUE THREAD

**Issue by Rmumford52** [OSSIndex/vulns#14]
This code appear on my Samsung Galaxy 8 cell phone as a text message. 
Just wondering if there's a fix for this issue.

**Comment by ken-duck** [comment]
Hi!

OSS Index does not have any code which works with SMS (cell phone texts) or cell phones in general. I suspect that what you are seeing is a google play purchase being paid by your cell phone carrier (it is something you can set up).

More information from here: https://botcrawl.com/dcb_association/

> ### What is DCB?
> 
> DCB is an abbreviation for Direct Carrier Billing, an online payment method that provides users with an option to make purchases by charging transactions to their mobile phone bill. Direct Carrier Billing is available on many platforms including smart TVs, computers, tablets, and phones. Android users also have the option to enable their mobile carriers as a payment method in the Google Play Store, Android apps, or Play Games app.
> 
> * When your mobile phone carrier is enabled as a payment method, Google Play Store sends an SMS to your carrier and a carrier specific code (example: TMobile — 11119999) with the text of “DCB_ASSOCIATION: ${authentication_hash}.”
> * The carrier receives the SMS and authenticates the ${authentication_hash} to ensure that the request originated from the Google Play Store, originated from your Google account, and came from your device.
> * ​The carrier now becomes enabled as a payment option in the Play Store (even if the transaction was not processed) and a text message may be sent to your phone that says DCB_ASSOCIATION followed by a code.
> 

I hope this helps
