### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/054ba9bf-bb26-40da-b19a-59eb9f248d0c

### ISSUE THREAD

**Issue by OrangeDog** [OSSIndex/vulns#15]
This issue was corrected in version 1.0.9.RELEASE of the affected packages.
The single range `[1.0.0-M6a,2.0.12)` is insufficient to express it.

**Comment by ken-duck** [comment]
Thanks for the correction. In fact, I think the [fix commit](https://github.com/spring-projects/spring-security-oauth/commit/0f43bb8c0de8be261479dc5d88926821f55468ca) even shows that `1.0.6.RELEASE` and higher are fixed. Is this your reading of it as well?

**Comment by ken-duck** [comment]
(The change should make its way out in the next day or so).

**Comment by OrangeDog** [comment]
> Is this your reading of it as well?

Yes, I think so. I hadn't expanded the tag list.

**Comment by Rmumford52** [comment]
To Ken,
I hope so because I found it on the Github website.   I hope it help you.
Rhonda

**Comment by Rmumford52** [comment]
Ken,
I know it is scary but., people do things illegal activities on my computer
and phone.   So, I joined the github.com for answers.
Thank you very much,
Rhonda Mumford

**Comment by Rmumford52** [comment]
I use to be a safeguard and security designer at a government facility.
Thank you so very much
Rhonda Mumford

**Comment by OrangeDog** [comment]
@Rmumford52 you seem to be confused. Please stop sending these emails.
GitHub is a hosting site for specific software projects, it's not somewhere to get general security answers or chat with people.

**Comment by Rmumford52** [comment]
To everyone,
Get the app called Who's on my wifi,  you might be surprised.
Because this is what I found.

**Comment by Rmumford52** [comment]
James, Steve, and Ken,
Get the app who's on my wifi.
This is what I found, if you put in the mac address you will be surprised.
Then, get the app called Fing.

**Comment by Rmumford52** [comment]
I'm still looking.   Trying hard to help and I am still having problems with my computer and Cell phone

**Comment by ken-duck** [comment]
Resolved. There is a package (spring-security-jwt) that was falsely implicated. I have also resolved that and it should disappear by tomorrow.

**Comment by Rmumford52** [comment]
Just go to the github and search under json

**Comment by Rmumford52** [comment]
I think its ready.
https://github.com/flori/json/blob/1c8416f4f36c1ec37b6ee8d94b4d0138cdfb3bfd/json.gemspec

Please double check

**Comment by OrangeDog** [comment]
@ken-duck if you can't block this person, can you at least mark everything off-topic?

**Comment by ken-duck** [comment]
Sorry for the delay. They have been blocked.
