### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/2a9810aa-3800-4e8e-8071-636e81c98386

### ISSUE THREAD

**Issue by OrangeDog** [OSSIndex/vulns#16]
Same problem in https://ossindex.sonatype.org/vuln/b8f2c30b-6527-485e-972e-f3e34e949a39

These were vulnerabilities in HttpClient 4 (apache-httpcomponents), not HttpClient 3 (commons-httpclient). Your database has them listed against both. Ideally remove all the erroneous affected components, or failing that add a lower bound (where missing) of `4.0.0`.

**Comment by ken-duck** [comment]
Good catch. I have made the change in our research data, which should find its way to the public database in the next day or so. Thanks!

**Comment by ken-duck** [comment]
Verified that it is correct in the public DB.
