### ISSUE TITLE
Incorrect vulnerability details - jetty-http 9.4.36.v20210114

### ISSUE THREAD

**Issue by y4ppieflu** [OSSIndex/vulns#165]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vulnerability/af695432-b5ea-4ab6-8b26-7843aadcfbf7?component-type=maven&component-name=org.eclipse.jetty.jetty-http
```

**Description**
The vulnerability in question affects jetty-http v9.4.36.v20210114, as correctly stated in the Affected Versions section. Nonetheless, the component page (https://ossindex.sonatype.org/component/pkg:maven/org.eclipse.jetty/jetty-http@9.4.36.v20210114) is missing the aforementioned vulnerability and thus the component may be incorrectly considered as non-vulnerable.

**Comment by ken-duck** [comment]
Thanks for pointing this out. This one is somewhat more complicated and is being passed to the dev team. The issue has to do with version range matching (which, as you might imagine, can be quite complicated due to every ecosystem and person having different version rules and what is acceptable).
