### ISSUE TITLE
Advisory: material-table dependency vulnerability 

### ISSUE THREAD

**Issue by tonycaud** [OSSIndex/vulns#175]
URL: https://github.com/mbrn/material-table/issues/2890
  format:  npm 
  namespace: npm scope
  name: material-table
  versions: <=1.69.3

A dependency of the component is reporting a vulnerability.

**Comment by ken-duck** [comment]
Thanks for the pointer. This has been resolved and should be in the public DB by sometime tomorrow.

**Comment by philbert440** [comment]
any update?

**Comment by ken-duck** [comment]
The vulnerability against the `jspdf` package has been added here: https://ossindex.sonatype.org/component/pkg:npm/jspdf@2.3.0

OSS Index does not directly report on vulnerabilities within dependencies, so you will not see any vulnerabilities on the matterial-table folder itself.

If you are using the API, then you need to check the transitive dependencies by name@version. You can get all the transitive dependency information from the packages.lock or yarn.lock files (should you be using npm or yarn). The [auditjs](https://github.com/sonatype-nexus-community/auditjs) tool works in  that manner.

If auditjs is not returning the appropriate vulnerability then we shall have to raise a bug against it, as the data appears to be available from the REST service (as linked above).

**Comment by ndonewar** [comment]
Closing this issue as it appears to be resolved. Please feel free to reopen or create a new issue if needed. Thanks!
