### ISSUE TITLE
Missing Vulnerabilities related to Kibana and modernizr

### ISSUE THREAD

**Issue by apdst** [OSSIndex/vulns#176]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL:  https://ossindex.sonatype.org/component/pkg:npm/kibana
  format: npm
  namespace:  https://ossindex.sonatype.org/component/pkg:npm/kibana
  name: Kibana
  versions: Version < 7.11.1
```

**More information**
Please refer the below URL:

https://snyk.io/vuln/search?q=Kibana&type=any

To facilitate future automation, please use the following format

**Advisory details**
```
  URL:  https://ossindex.sonatype.org/component/pkg:npm/modernizr
  format: npm
  namespace:  https://ossindex.sonatype.org/component/pkg:npm/modernizr
  name: modernizr
  versions: Version 3.3.1
```

**More information**
Please refer the below URL:

https://snyk.io/test/npm/modernizr/3.3.1

**Comment by apdst** [comment]
Also For Modernizr the vulnerabilities are missing:

https://snyk.io/test/npm/modernizr/3.3.1

**Comment by ken-duck** [comment]
Thank you for the heads up.

We have added the missing data for Kibana, and it should show in the public DB sometime tomorrow.

We have not added any new vulnerabilities to modernizr directly. It seems that the vulnerabilities listed against modernizr are actually from *transitive dependencies*. You will see these vulnerabilities if you look at the applicable packages (eg. https://ossindex.sonatype.org/component/pkg:npm/lodash@4.0.0)

The client scanner should determine the transitive dependencies and perform the appropriate queries from OSS Index, such as that done by the audit.js tool.

**Comment by apdst** [comment]
Thanks for the quick help.

@ken-duck I have observed the vulnerabilities in the below libraries as well:
  
  URL:  https://ossindex.sonatype.org/component/pkg:nuget/Microsoft.NETCore.App@2.1.0
  format:  Nuget
  namespace:  https://ossindex.sonatype.org/component/pkg:nuget/Microsoft.NETCore.App@2.1.0
  name: microsoft.netcore.app
  versions: 2.1.0
  Reference URL: https://snyk.io/vuln/nuget:microsoft.netcore.app

  URL:  https://ossindex.sonatype.org/component/pkg:nuget/iTextSharp@5.5.13
  format:  Nuget
  namespace:  https://ossindex.sonatype.org/component/pkg:nuget/iTextSharp@5.5.13
  name: iTextSharp
  versions: 5.5.13
  Reference URL: https://snyk.io/vuln/search?q=iTextSharp&type=any

  URL:  https://ossindex.sonatype.org/component/pkg:nuget/HtmlSanitizer@3.1.79
  format:  Nuget
  namespace:  https://ossindex.sonatype.org/component/pkg:nuget/HtmlSanitizer@3.1.79
  name: Htmlsanitizer
  versions: 3.1.79
  Reference URL: https://snyk.io/vuln/SNYK-DOTNET-HTMLSANITIZER-1055440

**Comment by apdst** [comment]
any update on this issue?

**Comment by ken-duck** [comment]
Whoops. I forgot to update. I did make some progress on several of these.

- You should see a vulnerability against ITextSharp though not against your specified version, however a couple of others that I added have not appeared in the public database. I am reasonably certain I know why; they are likely caught up in an automated process/review. I will give them a quick kick later on this evening and they should show up then.
- And several against Microsoft.NETCore.App: https://ossindex.sonatype.org/component/pkg:nuget/Microsoft.NETCore.App@2.1.0
- And also a couple against HtmlSanitizer (one for the version you were searching): https://ossindex.sonatype.org/component/pkg:nuget/HtmlSanitizer@3.1.79

Thanks for the heads up (and the reminder!)

**Comment by ken-duck** [comment]
Odd; the iTextSharp vulnerabilities are stuck in a different place in the pipeline. I am enlisting the help of the team involved in that code to help push things along. Sorry for the delay.

**Comment by apdst** [comment]
@ken-duck -No Worries and Thanks for the update. I will check the vulnerabilities and based on that will close the ticket.

**Comment by apdst** [comment]
@ken-duck - I have checked the vulnerabilities on Sonatype OSS Index & hence closing this ticket.
