### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vulnerability/39f9b1c0-a10d-4045-911e-ae51e37c8814

### ISSUE THREAD

**Issue by runkalicious** [OSSIndex/vulns#187]
**Vulnerability URL**
https://ossindex.sonatype.org/vulnerability/39f9b1c0-a10d-4045-911e-ae51e37c8814

**Description**
The vulnerability is reported based on this GitHub Issue in the `swagger-ui` project: https://github.com/swagger-api/swagger-ui/issues/5402

This Issue does not capture an active vulnerability within the project, but a request for easier sanitization when developing new functionality.

**Comment by ken-duck** [comment]
We agree with your assessment, and will remove the vulnerability. You should see it disappear sometime in the next day or two. Thanks for pointing this out.
