### ISSUE TITLE
Incorrect vulnerability details for json-logic-js

### ISSUE THREAD

**Issue by aikebah** [OSSIndex/vulns#190]
**Vulnerability URL**

```
https://ossindex.sonatype.org/vuln/0960b1d0-f1eb-49b3-8902-4e6ef95899ac
```

**Description**
Based on FP report in OWASP DependencyCheck (https://github.com/jeremylong/DependencyCheck/issues/3433) I ended up on the npmjs link also referenced in the OSSIndex issue (https://www.npmjs.com/advisories/1542), where it is clearly stated that version 2.0.1 is not vulnerable to the issue.
Nevertheless for version 2.0.1 (and 2.0.0) OSSIndex returns the vulnerability as present.

**Comment by ken-duck** [comment]
Thanks for the heads up. This issue has been updated and should show in the public database by sometime tomorrow.

**Comment by aikebah** [comment]
Verified as solved
