### ISSUE TITLE
Consider returning the references from the API

### ISSUE THREAD

**Issue by kapseliboi** [OSSIndex/vulns#193]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vulnerability/6225b8be-43bb-4407-84d3-e0179f3987bd
```

**Description**
The OSS Index API response doesn't include the references section which can be found on the webpage. It can be useful if you would like to identify duplicate vulnerabilities from multiple sources. In the example vulnerability the references section contains the NPM ID of the vulnerability but unfortunately it is missing from the API response. The only way to get that information now is to first get the API results and then one by one parse the contents of the webpages. OSS Index webpage is also heavily rate limited which makes this approach a pretty bad one and I would assume it's unwanted behaviour.

My suggestion would be to include that URL in the API response in a new field. What do you think?

**Comment by ndonewar** [comment]
Hi @kapseliboi - the OSS Index API now returns a field of `externalReferences` for each vulnerability entry. The field will contain a list of references as links. Those links will match the data that's seen on the web page of each vulnerability. Again, thanks for the suggestion!
