### ISSUE TITLE
Incorrect vulnerability details

### ISSUE THREAD

**Issue by takeshirs** [OSSIndex/vulns#199]
**Vulnerability URL**
Provide the URL to the vulnerability. For example:
```
https://ossindex.sonatype.org/vulnerability/e391a58d-4a81-448b-8ffc-e19016807d73?component-type=npm&component-name=btoa
```

**Component URL**
Provide the URL to the component. For example:
```
https://ossindex.sonatype.org/component/pkg:npm/btoa
```

**Description**
The referenced issue https://www.npmjs.com/advisories/646 mentions another package "atob" and seems not to be correlated to the package "btoa". Even more there is no version 2.0.3 for btoa as mentioned on vulnerability url. So I suggest to remove it.
Thanks.

**Comment by ken-duck** [comment]
Thanks for the heads up! The fix should show up in the public DB sometime tomorrow.

**Comment by StyleT** [comment]
Hi!
This is still an issue in the public DB
