### ISSUE TITLE
Bug: https://ossindex.sonatype.org/component/pkg:bower/lodash

### ISSUE THREAD

**Issue by rw530** [OSSIndex/vulns#20]
The cve records of the lodash library as a bower package and a npm package appears to be inconsistent. 

pkg:bower/lodash records no vulnerability.
![image](https://user-images.githubusercontent.com/30041957/61307701-b6a39000-a7e6-11e9-823c-5ae3b43ff52e.png)

Whereas pkg:npm/lodash records several critical vulnerabilities:
![image](https://user-images.githubusercontent.com/30041957/61307961-2285f880-a7e7-11e9-9f6c-c7bdfdb8f558.png)

Upon testing, the [prototype pollution](https://ossindex.sonatype.org/vuln/12e63c9c-b3f9-42d3-8541-dca1b72cad69) problem still exists in pkg:bower/lodash pre version 4.17.5.

**Comment by ken-duck** [comment]
This has been resolved in the internal data and should show up sometime tomorrow. Thanks for the tip-off.

**Comment by ken-duck** [comment]
Verified in product.
