### ISSUE TITLE
DLL injection to coa

### ISSUE THREAD

**Issue by blaky** [OSSIndex/vulns#209]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://github.com/veged/coa/issues/99
  format: npm
  namespace: N/A
  name: coa
  versions: 2.1.1, 2.1.3, 2.0.3, 2.0.4, 3.0.3,
```

**More information**
Please see https://github.com/veged/coa/issues/99 , it looks like someone published a "new" version of this unmaintained library and added a trojan DLL that executes malicious code on Windows machines. Since then, the version was removed from the public NPM repository, but the package could be cached on NPM proxy Nexus servers.

**Comment by TKr** [comment]
there are also 
2.1.1  and 2.0.4

![img](https://user-images.githubusercontent.com/6859933/140331520-9439cf67-5944-460d-be18-84479d4ec130.png)

https://github.com/veged/coa/issues/101

**Comment by blaky** [comment]
More info on: https://github.com/advisories/GHSA-73qr-pfmq-6rp8

**Comment by ken-duck** [comment]
Thanks for the heads up. This has been added and should show in the public database by sometime tomorrow.
