### ISSUE TITLE
Incorrect vulnerability details - false positive

### ISSUE THREAD

**Issue by hbingen** [OSSIndex/vulns#232]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vulnerability/d15c0c94-f572-4e34-ad62-b57dec1b1715?component-type=npm&component-name=node-os-utils
```

**Component URL**
```
https://ossindex.sonatype.org/component/pkg:npm/node-os-utils@1.3.6
```

**Description**
The advisory linked from this issue: https://github.com/advisories/GHSA-j9f8-8h89-j69x recommends upgrading to version >= 1.1.0
So node-os-utils 1.1.0 and above should be ok

**Comment by ken-duck** [comment]
Hi! Sorry for the delay, but I respond with good news.

OSS Index is going through a major upgrade, as described here: https://ossindex.sonatype.org/updates-notice

The most clear and obvious benefit is far fewer false negatives and false positives, and vulnerabilities will be added to the system on a much more frequent and rapid basis. Once the upgrade is completed you should see most (if not all) of the reported data issues be resolved.

**Comment by ken-duck** [comment]
Closing old issues. This particular issue was resolved by the aforementioned upgrade.
