### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vulnerability/674731ba-fcd9-43b6-95a5-8cdb74fd7514

### ISSUE THREAD

**Issue by JorisVanEijden** [OSSIndex/vulns#235]
**Vulnerability URL**
Provide the URL to the vulnerability. For example:
```
https://ossindex.sonatype.org/vulnerability/674731ba-fcd9-43b6-95a5-8cdb74fd7514
```

**Component URL**
Provide the URL to the component. For example:
```
https://ossindex.sonatype.org/component/pkg:composer/drupal/drupal@7.87.0
```

**Description**
Affected versions should be
8.5.0 - 8.5.15
8.6.0 - 8.6.15

7.87.0 Should not match.

**Comment by ken-duck** [comment]
Closing old issues. This particular issue was resolved by the aforementioned upgrade.
