### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/b6b072b4-1d2b-4e44-a3ad-cbff43fd7a07

### ISSUE THREAD

**Issue by tklancer** [OSSIndex/vulns#26]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/b6b072b4-1d2b-4e44-a3ad-cbff43fd7a07

**Description**
The CVSS score appears to be wrong. It's listed as a 7.5 in Sonatype, but there is a snyk.io report for the same issue that shows it as a 3.7. In addition, npm lists it as a "low", which seems more in line with the actual issue.

synk.io report: https://snyk.io/vuln/npm:clean-css:20180306

**Comment by ken-duck** [comment]
I'll take a look. Thanks for the heads up.

**Comment by ken-duck** [comment]
I have updated the vulnerability report to have a lower CVSS score (3.7). Thanks for the suggestion.

You should see this new value reflected by Saturday, or at the latest on Sunday (depends on how long it takes to work its way through the process).

**Comment by tklancer** [comment]
Looks good now. Thanks!

**Comment by ken-duck** [comment]
Great to hear :)
