### ISSUE TITLE
Bug: Incorrect vulnerability details sonatype-2021-1485 urfave/negroni

### ISSUE THREAD

**Issue by haydenmeade** [OSSIndex/vulns#279]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vulnerability/sonatype-2021-1485?component-type=golang&component-name=github.com/urfave/negroni
```

**Component URL**
```
https://ossindex.sonatype.org/component/pkg:golang/github.com/urfave/negroni
```

**Description**
This vulnerability references a Pull Request that wasn't merged.
```
https://github.com/urfave/negroni/pull/259
```

**Comment by ken-duck** [comment]
Sorry for the delay. We have been working on getting appropriate internal processes defined for dealing with data issues in the new data set. We are now working on catching up on the backlog.

This issue has been passed to the research team on our internal tracking system, and I will report back here once more is known.

**Comment by ken-duck** [comment]
The reference has been fixed to https://github.com/urfave/negroni/pull/261 

Thanks for the heads up
