### ISSUE TITLE
Incorrect vulnerability details for cytoscape (npm)

### ISSUE THREAD

**Issue by jimivdw** [OSSIndex/vulns#288]
**Vulnerability URL**
https://ossindex.sonatype.org/vulnerability/sonatype-2021-0541

**Component URL**
https://ossindex.sonatype.org/component/pkg:npm/cytoscape

**Description**
First of all, the referenced vulnerability (https://www.huntr.dev/bounties/1-npm-cytoscape/) is inaccessible:
> This report is not public

Secondly, the vulnerability type (CWE-1321) mentioned appears to be fixed in v3.21.0, but the latest versions (v3.21.1) still get reported as vulnerable by OSSIndex. The fix is in https://github.com/cytoscape/cytoscape.js/pull/2959, released as part of v3.21.0 (see https://github.com/cytoscape/cytoscape.js/compare/v3.20.2...v3.21.0).

**Comment by ken-duck** [comment]
Fix proof: https://ossindex.sonatype.org/component/pkg:npm/cytoscape@3.21.0
