### ISSUE TITLE
Missing all Open Liberty vulnerabilities

### ISSUE THREAD

**Issue by Kiiv** [OSSIndex/vulns#294]
**Advisory details**
```
  URL: [<Advisory URL>](https://openliberty.io/docs/latest/security-vulnerabilities.html)
  format: maven
  namespace: io.openliberty
  name: openliberty
  versions: multiple
```

**Comment by ken-duck** [comment]
Thanks for the heads up. You should find the appropriate vulnerability data available. Side note, it looks like there was only one version of the openliberty package, but the vulnerabilities were also assigned to the openliberty-runtime package, which has many more versions.
