### ISSUE TITLE
Bug: sonatype-2022-2100

### ISSUE THREAD

**Issue by lukaseder** [OSSIndex/vulns#300]
**Vulnerability URL**
Provide the URL to the vulnerability. For example:
```
https://ossindex.sonatype.org/vulnerability/sonatype-2022-2100
```

**Component URL**
Provide the URL to the component. For example:
```
https://ossindex.sonatype.org/component/pkg:maven/org.jooq/jooq
```

**Description**
The "vulnerability" is just listing a few XML export bugs, which have no impact on security. They also list a completely unrelated bug that doesn't even have anything to do with XML.

I wonder how this "vulnerability" came to be. Some automation false positive? I think such vulnerability reports should at least have some description about why a researcher thought this was going to be a risk.

**Comment by ryandens** [comment]
I encountered this as well - I'm glad this issue exists to help inform people of the false positive but it seems odd sonatype is flagging vulnerabilities without reaching out to maintainers or providing a justification.
