### ISSUE TITLE
Incorrect vulnerability details

### ISSUE THREAD

**Issue by revoltek-daniel** [OSSIndex/vulns#303]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vulnerability/sonatype-2019-0965
```

**Component URL**
```
https://ossindex.sonatype.org/component/pkg:composer/typo3fluid/fluid
```

**Description**
Should be fixed since 2.6.1 but is raised on 2.7.1

**Comment by ken-duck** [comment]
Sorry for the delay. We have been working on getting appropriate internal processes defined for dealing with data issues in the new data set. We are now working on catching up on the backlog.

This issue has been passed to the research team on our internal tracking system, and I will report back here once more is known.

**Comment by ken-duck** [comment]
Fixed: https://ossindex.sonatype.org/component/pkg:composer/typo3fluid/fluid@2.7.1
