### ISSUE TITLE
Incorrect versions in vulnerability

### ISSUE THREAD

**Issue by davecramer** [OSSIndex/vulns#319]
**Vulnerability URL**
Provide the URL to the vulnerability. For example:
```
https://ossindex.sonatype.org/vulnerability/sonatype-2022-4402
```

**Component URL**
Provide the URL to the component. For example:
```
https://github.com/pgjdbc/pgjdbc/commit/739e599d52ad80f8dcd6efedc6157859b1a9d637
```

**Description**
The commit above which is referenced in the vulnerability actually fixes the vulnerability
The correct effected versions < 42.2.26 42.3.x 42.4.0

See https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-r38f-c4h4-hqq2 for details.

Please update this ASAP.

**Comment by ken-duck** [comment]
From what I can tell, this has been fixed: https://ossindex.sonatype.org/component/pkg:maven/org.postgresql/postgresql@42.2.26
