### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/3e831af5-428b-4712-874f-8f6ff932e2b2

### ISSUE THREAD

**Issue by skoofer** [OSSIndex/vulns#32]
https://ossindex.sonatype.org/vuln/3e831af5-428b-4712-874f-8f6ff932e2b2

npm advisory suggests for bootstrap:

> For bootstrap 4.x upgrade to 4.3.1 or later. For bootstrap 3.x upgrade to 3.4.1 or later.

However, version range in ossindex is  `(,4.3.1),[3.0.0,3.4.1)` which ends up flagging version 3.4.1 as vulnerable where it is not

**Comment by ken-duck** [comment]
Thanks for the help! I'll put in a fix shortly, and it should work its way through the process by tomorrow morning.

**Comment by ken-duck** [comment]
And I will see about writing in some checks that will detect these sorts of mistakes as well.

**Comment by ken-duck** [comment]
I just double checked the results, and they look correct. Thanks for the heads up!
