### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/95474f7e-9331-4ffe-abf1-06e16e2e4f57

### ISSUE THREAD

**Issue by dlinszner** [OSSIndex/vulns#34]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/95474f7e-9331-4ffe-abf1-06e16e2e4f57

**Description**
npm advisory suggests:
`Upgrade to version 0.7.2 or later.`

However, the range in ossindex is [0.7.2,) which ends up reversing all findings.

**Comment by ken-duck** [comment]
Bugger. Sorry about that. I am fixing now, it should through the process by tomorrow.

I am working on adding additional validation to try and prevent these issues in the future.

**Comment by ken-duck** [comment]
I just checked the link, and the range looks to be corrected. Thanks for the heads up!
