### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/d96c07dd-81f9-41f6-b2bd-531143bcaeab

### ISSUE THREAD

**Issue by dallinskinner** [OSSIndex/vulns#42]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/d96c07dd-81f9-41f6-b2bd-531143bcaeab

**Description**
The vulnerability is flagging quill 1.3.7 for a problem that existed in 1.3.6 and was fixed in 1.3.7. The linked [npm advisory](https://www.npmjs.com/advisories/1039) says versions _prior to 1.3.7_ are affected. There are also links to both the [issue](https://github.com/quilljs/quill/issues/2438) and the [resultant PR](https://github.com/quilljs/quill/pull/2674) which you can see was merged and released.

**Comment by ken-duck** [comment]
This has been fixed in our research DB, and should be public by tomorrow. Thanks for the heads up! I also removed a duplicate finding of the same vulnerability at the same time.

**Comment by ken-duck** [comment]
Cleaning things up: it looks like the data is correct now: https://ossindex.sonatype.org/vuln/d96c07dd-81f9-41f6-b2bd-531143bcaeab
