### ISSUE TITLE
Incorrect vulnerability details of bootstrap@3.3.5

### ISSUE THREAD

**Issue by shounakitraj** [OSSIndex/vulns#45]
**Vulnerability URL**
Vuln of bootstrap 3.3.5 is not reported. So it is False Negative.

**Description**
I am using Sonatype vulnerability Database for listing vulnerable versions of libraries. My list contains bootstrap with version 3.3.5. This version of bootstrap is vulnerable to multiple vulnerabilities (https://snyk.io/test/npm/bootstrap/3.3.5)

But the sonatype db is not listing this version of bootstrap as vulnerable version. Could you please check and let me know if more information is required.

**Comment by ken-duck** [comment]
What tool are you using for the query, or are you checking the REST API directly? I see the vulnerabilities on the website here:

https://ossindex.sonatype.org/component/pkg:npm/bootstrap@3.3.5

But it is possible that I am checking a different package manager (maven, npm, nuget?), or perhaps there is a bug in the tool you are using.

**Comment by msymons** [comment]
The tool is Dependency-Track.  I have updated [this issue](/DependencyTrack/dependency-track/issues/501) with some observations pertaining to case-sensitivity (Bootstrap bad, bootstrap good) but there may be an HTTP 400 involved as well.

**Comment by ken-duck** [comment]
Ah, I see. I shall have to look into the case problem in npm. Thanks for letting me know.

**Comment by shounakitraj** [comment]
Thank you @msymons for updating the issue.

Yes the tool is Dependency-Track as Mark has said earlier there might be couple of reasons.

Reason 1 Case sensitivity
Case sensitivity: But as per my observation OSSindex does not flag either pkg:nuget/bootstrap@3.3.5 or pkg:nuget/Bootstrap@3.3.5 (I have tried both the cases). Either I might be missing something obvious or there is actual bug.

Reason 2 400 Error
I am seeing 400 Response error in Dependency-Track logs. Is it the reason because of which these vulns are not getting flagged as vulnerable version.
`17:16:50.078 WARN [OssIndexAnalysisTask] Received unexpected HTTP response 400 Bad Request`

**Note:** I am using OSSIndex username as API name and API key from the account settings.

Let me know if I can help with more information.

**Comment by ken-duck** [comment]
@shounakitraj It is strange you see the case problem in nuget. I am getting vulnerabilities for the all lowercase version:

https://ossindex.sonatype.org/component/pkg:nuget/bootstrap@3.3.5
vs
https://ossindex.sonatype.org/component/pkg:nuget/Bootstrap@3.3.5

I am definitely interested in these "bad requests". Often they are the result of a malformed PURL. I am not certain on the best way to proceed on that front. You don't happen to have a list of PURLs that are sent on that query do you?

**Comment by ken-duck** [comment]
@msymons It is almost certainly the 400 error in your case as well, since I have not been able to reproduce the problem on the API either. Same question as above for you:

> Often they are the result of a malformed PURL. I am not certain on the best way to proceed on that front. You don't happen to have a list of PURLs that are sent on that query do you?

Otherwise I might be able to install DependencyTrack to try and reproduce the problem. My plate is rather full and I have been falling behind lately, but am hoping to catch up this week. Note that we are getting new team members shortly that will help reduce the load.

**Comment by shounakitraj** [comment]
@ken-duck 

Sorry for the late response. But I am still facing the issue that the Dependency Track does have False Negative for bootstrap 3.3.5

The PURL for this is: <purl>pkg:nuget/bootstrap@3.3.5</purl>

Could you please help me with this? Also let me know if you require any more information.

**Comment by shounakitraj** [comment]
@ken-duck 

Did you get chance to look into issue mentioned above?

I have got few more findings like this:
JQuery | 3.3.1: pkg:nuget/jQuery@3.3.1
JQuery | 2.1.1: pkg:nuget/jQuery@2.1.1
AngularJS | 1.5.9 : pkg:nuget/AngularJS@1.5.9
AngularJS | 1.5.3 : pkg:nuget/AngularJS@1.5.3

**Comment by ken-duck** [comment]
I rewrote some code that hopefully might have handled some related errors, but have not resolved your issue yet. Sorry for the delay. I will install DependencyTrack today and try and track down the problem.

I will update later on today on whether I am able to reproduce the problem or not.

**Comment by ken-duck** [comment]
Alright. I got Dependency Track working, and have started adding in dependencies by hand.

<img width="1590" alt="Screen Shot 2019-12-05 at 1 15 59 PM" src="https://user-images.githubusercontent.com/30352045/70257822-732fcb00-1761-11ea-8713-03da406605de.png">

Curiously, you will see that bootstrap@3.3.5 gives me vulnerabilities. To further debug this one I will need to know what the package URL (PURL) is you are using. Can you go to the component details (extended tab) and pass on the details of what you see there? I have this currently for my test:

<img width="598" alt="Screen Shot 2019-12-05 at 1 15 45 PM" src="https://user-images.githubusercontent.com/30352045/70257935-ad996800-1761-11ea-8e2e-6224dc001889.png">

I will start putting in your other findings and see what I can find out.

**Comment by ken-duck** [comment]
A few more notes:I show vulnerabilities for pkg:nuget/jQuery@3.3.1

**Comment by ken-duck** [comment]
@shounakitraj Could you by any chance send me your bom? I need to figure out which ones are causing the exceptions you are seeing. We can arrange a more secure channel if you would prefer.

**Comment by shounakitraj** [comment]
@ken-duck Thanks for the detailed explanation. Could you share your email where I can share the bom xml file as I need to remove some internal libraries from it.

I think I have narrowed down the issue as follows:
1. Total number of packages in bom.xml: 179
2. While parsing the xml it gives error of unable to parse PackageURL for 127 packages.
3. Due to this even other packages with known vulnerabilities are also not getting listed.
4. I need to check the exact package names from [nuget URL](https://www.nuget.org/packages/) and try to create new bom.xml manually for each package and upload to check once.

The package names that are being used in bom.xml are creating false negatives.I will try once with correct packages names getting from [nuget URL](https://www.nuget.org/packages/)

**Comment by shounakitraj** [comment]
After using correct packages names for bootstrap, angularjs now the vulnerability count has increased and it is listing known vulnerabilities for the respective packages.

![image](https://user-images.githubusercontent.com/25792555/70308482-5f539a00-1831-11ea-96c8-638057f36702.png)

**Comment by ken-duck** [comment]
The case sensitivity is a pain. I have a different issue that shows that NuGet 3.0 expects all lower case names, whereas NuGet 2.0 was case sensitive. We are in an awkward position at the moment. We will likely be forcing the API to be case insensitive in the not too far future, which will make this problem moot.

**Comment by ken-duck** [comment]
Send your BOM if possible to kduck at sonatype dot com. What I am looking for are two things:

1. Incorrect cases
2. and more importantly, PURLs that might be breaking OSS Index (causing the exceptions you have been seeing)

**Comment by ndonewar** [comment]
Closing this older issue as it appears to be resolved. API requests for NuGet packages are no longer handled in a case-sensitive manner, and the original package posted is returning vulnerabilities.
Please feel free to reopen or create a new issue if needed. Thanks!
