### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/c87480a0-f84a-4381-9856-d2be20e3e30c

### ISSUE THREAD

**Issue by palfrey** [OSSIndex/vulns#46]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vuln/c87480a0-f84a-4381-9856-d2be20e3e30c
```

**Description**
CVSS Score is listed as "unscored" when the links have it at either 5.0 or 7.5 depending on which one you use.

**Comment by ken-duck** [comment]
Odd. Thanks for letting us know. I will look into the issue today.

**Comment by palfrey** [comment]
@ken-duck Still seeing this issue. Any thoughts on the matter?

**Comment by ken-duck** [comment]
Sorry for the delay. There is definitely a bug that I am working on resolving. I am hoping to have it up and running this week (perhaps even today if things go well).

**Comment by palfrey** [comment]
Fixed now. Thanks!
