### ISSUE TITLE
Advisory: xss vulnerability in ssr in vuejs 

### ISSUE THREAD

**Issue by nikhilgeo** [OSSIndex/vulns#55]
**Advisory details**
```
  URL: https://snyk.io/vuln/npm:vue:20180802
  format: bower
  namespace: <maven groupid, npm scope, etc.>
  name: vue
  versions: <2.5.17
```

**More information**
https://github.com/vuejs/vue/commit/c28f79290d57240c607d8cec3b3413b49702e1fb
https://github.com/vuejs/vue/releases/tag/v2.5.17
https://twitter.com/vuejs/status/1024754536877973504

**Comment by ken-duck** [comment]
Sorry for the delay. This has been added across multiple ecosystems and should show up tomorrow.

FYI, we are expanding the team come the new year, which should allow us to respond to requests faster in the future.

Thanks for the help.

**Comment by ken-duck** [comment]
At long last: https://ossindex.sonatype.org/component/pkg:bower/vue@2.5.16
