### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/06e60262-8241-42ef-8f64-e3d72091de19

### ISSUE THREAD

**Issue by SVilgelm** [OSSIndex/vulns#58]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vuln/06e60262-8241-42ef-8f64-e3d72091de19
```

**Description**
It's been fixed Jan 27, 2019: https://github.com/pypa/setuptools/pull/1640
and the fix is released in the v40.8.0: https://github.com/pypa/setuptools/commits/v40.8.0

**Comment by SVilgelm** [comment]
@ken-duck Could you take a look at this issue?

**Comment by SVilgelm** [comment]
@ken-duck what about this issue?

**Comment by ken-duck** [comment]
Yup. On it.

FYI, we are working on a new process where the research team will be taking over the bug reports. This should speed up fixes (I am pulled in too many directions and am not fast enough on my own, plus we need someone to work them when I am unavailable). This should kick in sometime this month.

Meanwhile I will endeavour to look into this one today.

**Comment by SVilgelm** [comment]
No worries, thank you so much. This and #59 are very important, almost all python projects are affected by these bugs. I added ignores for those bugs in all python projects I'm working on

**Comment by ken-duck** [comment]
Ya, understood. The changes have been made and should make it to the public database by tomorrow. Thanks for the help, and definitely thank you for bumping the issue. It is definitely an important one to have right!

**Comment by SVilgelm** [comment]
thanks

**Comment by ken-duck** [comment]
Closing out old issues. A manual check indicates this has been resolved. Thanks for the help!
