### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/3d8a020a-8863-4811-aeef-f086e77d7167

### ISSUE THREAD

**Issue by gotthardp** [OSSIndex/vulns#60]
There is no CVSS vector (and no score). As a general rule, do you leave some reports without any classification or is it an omission?
The referenced source says it's "medium", but with no reasons. IMHO it could be e.g.
```
CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N
```
High complexity network attack, no impact on availability, low in confi/integ as the loss is not complete. What do you think?

**Comment by ken-duck** [comment]
Sorry for the delay. I have made the suggested changes and they should be publicly visible sometime tomorrow.

As a general rule we always supply a CWE and a CVSS score. That general rule was put in place perhaps not *too* long after this particular issue was added (sometime in 2018, anyhow). You should not be able to find any new issues missing this data unless something has gone catastrophically wrong.

Sorry again for the delay. I am trying to catch up on all issues now, and we are putting processes (and a team!) in place to try and deal with issues on a much faster basis in the near future.

**Comment by gotthardp** [comment]
Thanks!
