### ISSUE TITLE
Incorrect vulnerability details

### ISSUE THREAD

**Issue by kenime** [OSSIndex/vulns#65]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/component/pkg:npm/cryptiles@3.1.4
```

**Description**
Describe what is wrong with the vulnerability details

The 2 vulnerabilities are fixed in [3.1.3, 4.0.0), [reference link](https://github.com/hapijs/cryptiles/issues/35)

**Comment by ken-duck** [comment]
Fixed. All going well this should be visible in the public DB by sometime tomorrow. Thanks for letting us know!

**Comment by ken-duck** [comment]
I just manually verified that the vulnerability ranges look correct, and are not reported against the supplied link: https://ossindex.sonatype.org/component/pkg:npm/cryptiles@3.1.4

Closing!
