### ISSUE TITLE
Incorrect vulnerability details c97f4ae7-be1f-4f71-b238-7c095b126e74 (node-sass)

### ISSUE THREAD

**Issue by msymons** [OSSIndex/vulns#73]
**Vulnerability URL*
```
https://ossindex.sonatype.org/vuln/c97f4ae7-be1f-4f71-b238-7c095b126e74
```

**Description**
Version range in OSS Index is `(0.0.0,)`

However, the linked advisory:

https://www.npmjs.com/advisories/961

...states "Upgrade to version 4.13.1 or later".

**Comment by ken-duck** [comment]
You are quite correct. This has been fixed and should show up tomorrow. Sorry about that.

I will do a DB sweep to see if there are others. Meanwhile we are also discussing the error with the researchers to try and prevent it from happening in the future.

Thanks for the submission.

**Comment by ken-duck** [comment]
It is fixed for node_sass, but for some reason the other modules did not get the update. I am going to try and force a refresh for those packages.

**Comment by ken-duck** [comment]
Visual confirmation indicates this has been resolved.
