### ISSUE TITLE
Incorrect vulnerability details npm-1467 (cordova-plugin-inappbrowser)

### ISSUE THREAD

**Issue by msymons** [OSSIndex/vulns#74]
**Vulnerability URL**

```
https://ossindex.sonatype.org/vuln/7a38e713-e3c7-4850-b464-60d6c9a9b5c3
```

**Description**
Impacts `cordova-plugin-inappbrowser`.

The OSS Index version range is listed as `(3.1.0,)`.   ie, versions after 3.1.0.  This is the reverse of what is stated in [NPM Advisory 1467](https://www.npmjs.com/advisories/1467) where remediation is "Upgrade to version 3.1.0 or later.".

Thus, should not the version range be `(,3.1.0)` ?

**Comment by ken-duck** [comment]
You are quite correct. This has been fixed and should show up tomorrow. Sorry about that.

I will do a DB sweep to see if there are others. Meanwhile we are also discussing the error with the researchers to try and prevent it from happening in the future.

Thanks for the submission.

**Comment by msymons** [comment]
I see that `cordova-plugin-inappbrowser` has now had the version range tweaked.  That's great.  However, looking at the Vulnerability URL, it seems that none of of the other affected components have yet been updated.  eg:

`pkg:bower/cordova-plugin-onabrowser`

**Comment by ken-duck** [comment]
It seems that the updates were not pushed properly to associated packages. I am trying to push the changes through in the next load and will shepherd them through the process.

**Comment by ken-duck** [comment]
Visual confirmation that the data is correct now. I understand the mechanism why it failed to propagate the first time. I can *manually* correct things, but the code for automatically correcting it will take a bit longer. I will document the manual process for now, but *do* have a spring in a few weeks dedicated to problems like these.
