### ISSUE TITLE
Incorrect vulnerability details - e7bea77b-f37f-4290-a069-08fc9c4b6ac0

### ISSUE THREAD

**Issue by taykunats** [OSSIndex/vulns#78]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vuln/e7bea77b-f37f-4290-a069-08fc9c4b6ac0
```

**Description**

The advisory https://www.npmjs.com/advisories/1488 
mentions that version acorn@6.4.1 has already remediated the vulnerability. however 
https://ossindex.sonatype.org/component/pkg:npm/acorn@6.4.1 still tags the version as having this vulnerability.

**Comment by taykunats** [comment]
also include https://ossindex.sonatype.org/component/pkg:npm/acorn@5.7.4 which is also mentioned in the advisory.

**Comment by ken-duck** [comment]
Thanks for the heads up. This has been corrected and should be visible in the public database by tomorrow sometime.

**Comment by ken-duck** [comment]
Cleaning up old issues. Both of the linked coordinates show as non-vulnerable. Thanks for your help!
