### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/58d5ff2d-6015-4ec9-bcbd-69a9378be14f

### ISSUE THREAD

**Issue by scolytus** [OSSIndex/vulns#82]
**Vulnerability URL**
https://ossindex.sonatype.org/vuln/58d5ff2d-6015-4ec9-bcbd-69a9378be14f

**Description**
Wrong reporting on older versions. According to advisory only 6.0.0, 6.0.1 and 6.0.2 are affected. These are false positives according to advisory:
https://ossindex.sonatype.org/component/pkg:npm/kind-of@4.0.0
https://ossindex.sonatype.org/component/pkg:npm/kind-of@5.1.0

**Comment by ken-duck** [comment]
Thanks for the heads up. I have submitted the change and it should become visible in the next day or so in the public database, all going well.

**Comment by ken-duck** [comment]
Visual confirmation indicates this has been corrected.
