### ISSUE TITLE
Incorrect vulnerability details - https://ossindex.sonatype.org/vuln/2231fe55-3b80-4ab3-8d07-8ca04aa0622a

### ISSUE THREAD

**Issue by DarthHater** [OSSIndex/vulns#84]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/component/pkg:gem/activerecord@6.0.2.2
https://ossindex.sonatype.org/vuln/2231fe55-3b80-4ab3-8d07-8ca04aa0622a
```

**Description**
Describe what is wrong with the vulnerability details

This version of activerecord being flagged as vulnerable seems wrong.

Looking at the version range and details on the CVE:

```
SQL injection vulnerability in activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb in the PostgreSQL adapter for Active Record in Ruby on Rails 2.x and 3.x before 3.2.19 allows remote attackers to execute arbitrary SQL commands by leveraging improper bitstring quoting.
```

Seems to indicate it was fixed long ago, so I'm unsure why this version is flagged.

**Comment by ken-duck** [comment]
This has been resolved and should show up in the public database tomorrow.

**Comment by ken-duck** [comment]
Cleaning up old issues. This version no longer shows as vulnerable.
