### ISSUE TITLE
Incorrect vulnerability details - a0172c09-270c-4d3c-9816-564f20f372db

### ISSUE THREAD

**Issue by scolytus** [OSSIndex/vulns#90]
**Vulnerability URL**

```
https://ossindex.sonatype.org/vuln/a0172c09-270c-4d3c-9816-564f20f372db
```

**Description**

Version selector is broken. See affected versions: 
https://www.npmjs.com/advisories/1179/versions

This should be covered by the vulnerability:

* https://ossindex.sonatype.org/component/pkg:npm/minimist@1.2.0
* https://ossindex.sonatype.org/component/pkg:npm/minimist@1.2.1
* https://ossindex.sonatype.org/component/pkg:npm/minimist@1.2.2

**Comment by ken-duck** [comment]
Bah. Sorry, this somehow slipped through the cracks. It has been resolved and should show up sometime tomorrow, all going well.

**Comment by ndonewar** [comment]
Closing this older issue as it appears to be resolved. Please feel free to reopen or create a new issue if needed. Thanks!
