### ISSUE TITLE
Missing Advisory org.http4s:http4s-server_2.12

### ISSUE THREAD

**Issue by ivars-vids** [OSSIndex/vulns#94]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://github.com/advisories/GHSA-66q9-f7ff-mmx6
  format: maven
  namespace: org.http4s
  name: http4s-server_2.12
  versions: before versions 0.18.26, 0.20.20, and 0.21.2
```

**More information**
Any additional information that might be useful/interesting

**Comment by ken-duck** [comment]
Sorry for the delay. This has been added and should show up by sometime tomorrow.

**Comment by ken-duck** [comment]
I have confirmed that the issue is there: https://ossindex.sonatype.org/vuln/39c7bce2-e06d-414c-bc06-af11269560ae
