### ISSUE TITLE
Incorrect vulnerability details

### ISSUE THREAD

**Issue by jtgasper3** [OSSIndex/vulns#97]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/vuln/00b3f4b6-25fa-442f-926f-58d34ed45456
```

**Description**
Having consulted with some of the core Java CAS client developers, this bug was fixed in v3.6.0 and is no longer in 3.6.1.  Here's a link to other details including the pull request that fixes the issue: https://snyk.io/vuln/SNYK-JAVA-ORGJASIGCASCLIENT-31192

Thanks

**Comment by ken-duck** [comment]
Thanks for the heads up. This has been resolved and should show up sometime tomorrow.

**Comment by jtgasper3** [comment]
Thank you. It looks good now.
